[2024-02-02T10:35:23.741+0000] {processor.py:153} INFO - Started process (PID=838) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:23.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:23.744+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:23.743+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:23.797+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:23.779+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_da import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.bash_da'
[2024-02-02T10:35:23.797+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:23.966+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.246 seconds
[2024-02-02T10:35:29.122+0000] {processor.py:153} INFO - Started process (PID=853) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:29.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:29.125+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:29.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:29.136+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:29.135+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_da import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.bash_da'
[2024-02-02T10:35:29.137+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:29.181+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.065 seconds
[2024-02-02T10:35:34.277+0000] {processor.py:153} INFO - Started process (PID=866) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:34.278+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:34.279+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:34.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:34.295+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:34.294+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_da import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.bash_da'
[2024-02-02T10:35:34.296+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:34.340+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.074 seconds
[2024-02-02T10:35:39.711+0000] {processor.py:153} INFO - Started process (PID=892) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:39.718+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:39.719+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:39.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:39.750+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:39.739+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_da import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.bash_da'
[2024-02-02T10:35:39.751+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:39.815+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.115 seconds
[2024-02-02T10:35:40.907+0000] {processor.py:153} INFO - Started process (PID=895) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:40.908+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:40.909+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:40.909+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:40.983+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:40.981+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashOperator
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:35:40.989+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:41.082+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.198 seconds
[2024-02-02T10:35:44.868+0000] {processor.py:153} INFO - Started process (PID=907) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:44.869+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:44.870+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:44.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:44.878+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:44.877+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:35:44.879+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:44.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.038 seconds
[2024-02-02T10:35:50.099+0000] {processor.py:153} INFO - Started process (PID=921) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:50.099+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:50.100+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:50.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:50.107+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:50.106+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:35:50.107+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:50.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.038 seconds
[2024-02-02T10:35:55.640+0000] {processor.py:153} INFO - Started process (PID=942) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:55.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:55.641+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:55.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:55.649+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:55.648+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:35:55.649+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:55.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.053 seconds
[2024-02-02T10:35:56.679+0000] {processor.py:153} INFO - Started process (PID=949) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:35:56.680+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:35:56.682+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:56.682+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:56.695+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:35:56.693+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:35:56.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:35:56.729+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.056 seconds
[2024-02-02T10:36:02.010+0000] {processor.py:153} INFO - Started process (PID=964) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:02.011+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:02.012+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:02.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:02.043+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:02.037+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:02.043+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:02.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.115 seconds
[2024-02-02T10:36:04.883+0000] {processor.py:153} INFO - Started process (PID=972) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:04.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:04.890+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:04.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:04.903+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:04.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:04.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:04.941+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.064 seconds
[2024-02-02T10:36:09.277+0000] {processor.py:153} INFO - Started process (PID=984) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:09.278+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:09.280+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:09.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:09.290+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:09.289+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:09.290+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:09.319+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.047 seconds
[2024-02-02T10:36:10.576+0000] {processor.py:153} INFO - Started process (PID=998) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:10.577+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:10.578+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:10.578+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:10.588+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:10.587+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:10.589+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:10.620+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.052 seconds
[2024-02-02T10:36:13.860+0000] {processor.py:153} INFO - Started process (PID=1011) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:13.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:13.863+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:13.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:13.876+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:13.874+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:13.876+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:13.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.061 seconds
[2024-02-02T10:36:15.263+0000] {processor.py:153} INFO - Started process (PID=1014) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:15.269+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:15.274+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:15.273+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:15.300+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:15.299+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:15.301+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:15.329+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.088 seconds
[2024-02-02T10:36:17.585+0000] {processor.py:153} INFO - Started process (PID=1018) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:17.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:17.591+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:17.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:17.614+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:17.612+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:17.615+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:17.645+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.075 seconds
[2024-02-02T10:36:19.798+0000] {processor.py:153} INFO - Started process (PID=1030) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:19.800+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:19.801+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:19.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:19.814+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:19.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:19.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:19.852+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.060 seconds
[2024-02-02T10:36:23.260+0000] {processor.py:153} INFO - Started process (PID=1034) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:23.264+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:23.267+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:23.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:23.283+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:23.282+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:23.284+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:23.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.077 seconds
[2024-02-02T10:36:25.983+0000] {processor.py:153} INFO - Started process (PID=1055) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:25.984+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:25.985+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:25.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:25.998+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:25.996+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:25.999+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:26.034+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.059 seconds
[2024-02-02T10:36:28.457+0000] {processor.py:153} INFO - Started process (PID=1062) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:28.458+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:28.459+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:28.459+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:28.471+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:28.470+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:28.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:28.504+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.053 seconds
[2024-02-02T10:36:33.721+0000] {processor.py:153} INFO - Started process (PID=1076) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:33.722+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:33.723+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:33.723+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:33.734+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:33.732+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:33.734+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:33.767+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.052 seconds
[2024-02-02T10:36:36.371+0000] {processor.py:153} INFO - Started process (PID=1084) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:36.372+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:36.372+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:36.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:36.380+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:36.379+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:36.380+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:36.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.040 seconds
[2024-02-02T10:36:41.484+0000] {processor.py:153} INFO - Started process (PID=1109) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:41.503+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:41.504+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:41.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:41.517+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:41.515+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:41.517+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:41.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.091 seconds
[2024-02-02T10:36:42.162+0000] {processor.py:153} INFO - Started process (PID=1115) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:42.163+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:42.165+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:42.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:42.175+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:42.173+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:42.176+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:42.238+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.083 seconds
[2024-02-02T10:36:43.755+0000] {processor.py:153} INFO - Started process (PID=1120) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:43.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:43.757+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:43.757+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:43.767+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:43.766+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:43.768+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:43.851+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.101 seconds
[2024-02-02T10:36:49.206+0000] {processor.py:153} INFO - Started process (PID=1133) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:49.207+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:49.208+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:49.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:49.217+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:49.216+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:49.217+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:49.241+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.042 seconds
[2024-02-02T10:36:50.411+0000] {processor.py:153} INFO - Started process (PID=1136) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:50.415+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:50.420+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:50.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:50.457+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:50.453+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:50.459+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:50.530+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.139 seconds
[2024-02-02T10:36:55.884+0000] {processor.py:153} INFO - Started process (PID=1163) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:55.885+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:55.886+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:55.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:55.897+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:55.895+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:36:55.898+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:55.931+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.052 seconds
[2024-02-02T10:36:58.392+0000] {processor.py:153} INFO - Started process (PID=1169) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:58.393+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:58.394+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:58.394+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:58.398+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:58.397+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1 >> task2
                  ^
SyntaxError: unexpected EOF while parsing
[2024-02-02T10:36:58.399+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:58.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.055 seconds
[2024-02-02T10:36:59.932+0000] {processor.py:153} INFO - Started process (PID=1177) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:36:59.933+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:36:59.934+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:59.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:59.938+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:36:59.937+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1, >> task2
             ^
SyntaxError: invalid syntax
[2024-02-02T10:36:59.939+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:36:59.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.036 seconds
[2024-02-02T10:37:04.426+0000] {processor.py:153} INFO - Started process (PID=1192) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:04.427+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:04.428+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:04.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:04.431+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:04.430+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1, >> task2
             ^
SyntaxError: invalid syntax
[2024-02-02T10:37:04.432+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:04.457+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.034 seconds
[2024-02-02T10:37:09.140+0000] {processor.py:153} INFO - Started process (PID=1208) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:09.142+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:09.143+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:09.143+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:09.147+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:09.145+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1, >> task2
             ^
SyntaxError: invalid syntax
[2024-02-02T10:37:09.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:09.180+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.046 seconds
[2024-02-02T10:37:10.597+0000] {processor.py:153} INFO - Started process (PID=1216) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:10.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:10.611+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:10.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:10.624+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:10.621+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1, >> task2
             ^
SyntaxError: invalid syntax
[2024-02-02T10:37:10.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:10.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.123 seconds
[2024-02-02T10:37:13.557+0000] {processor.py:153} INFO - Started process (PID=1222) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:13.558+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:13.560+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:13.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:13.570+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:13.563+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1, >> task2
             ^
SyntaxError: invalid syntax
[2024-02-02T10:37:13.571+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:13.718+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.169 seconds
[2024-02-02T10:37:16.522+0000] {processor.py:153} INFO - Started process (PID=1233) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:16.528+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:16.529+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:16.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:16.534+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:16.532+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1, >> task2
             ^
SyntaxError: invalid syntax
[2024-02-02T10:37:16.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:16.580+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.063 seconds
[2024-02-02T10:37:22.191+0000] {processor.py:153} INFO - Started process (PID=1248) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:22.192+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:22.193+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:22.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:22.197+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:22.196+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1,tas >> task2
                      ^
SyntaxError: unexpected EOF while parsing
[2024-02-02T10:37:22.198+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:22.233+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.048 seconds
[2024-02-02T10:37:25.696+0000] {processor.py:153} INFO - Started process (PID=1253) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:25.698+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:25.699+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:25.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:25.711+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:25.702+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1,task2, >> task2
                   ^
SyntaxError: invalid syntax
[2024-02-02T10:37:25.712+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:25.753+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.072 seconds
[2024-02-02T10:37:27.204+0000] {processor.py:153} INFO - Started process (PID=1267) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:27.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:27.207+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:27.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:27.211+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:27.210+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1,task2,ta >> task2
                           ^
SyntaxError: unexpected EOF while parsing
[2024-02-02T10:37:27.212+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:27.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.059 seconds
[2024-02-02T10:37:27.740+0000] {processor.py:153} INFO - Started process (PID=1272) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:27.741+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:27.742+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:27.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:27.773+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:27.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1,task2,task3 >> task2
                              ^
SyntaxError: unexpected EOF while parsing
[2024-02-02T10:37:27.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:27.868+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.138 seconds
[2024-02-02T10:37:29.472+0000] {processor.py:153} INFO - Started process (PID=1282) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:29.475+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:29.476+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:29.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:29.519+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:29.517+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:37:29.526+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:29.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.117 seconds
[2024-02-02T10:37:31.511+0000] {processor.py:153} INFO - Started process (PID=1283) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:31.511+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:31.512+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:31.512+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:31.520+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:31.519+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:37:31.521+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:31.544+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.039 seconds
[2024-02-02T10:37:36.832+0000] {processor.py:153} INFO - Started process (PID=1298) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:36.834+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:36.835+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:36.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:36.844+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:36.843+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:37:36.845+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:36.878+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.052 seconds
[2024-02-02T10:37:38.547+0000] {processor.py:153} INFO - Started process (PID=1307) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:38.548+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:38.549+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:38.549+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:38.556+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:38.556+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:37:38.557+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:38.578+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.035 seconds
[2024-02-02T10:37:41.329+0000] {processor.py:153} INFO - Started process (PID=1314) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:41.330+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:41.331+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:41.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:41.339+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:41.338+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:37:41.339+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:41.371+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.046 seconds
[2024-02-02T10:37:43.864+0000] {processor.py:153} INFO - Started process (PID=1328) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:43.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:43.876+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:43.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:43.884+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:43.882+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1,task2,task3] >> tas task2
                                   ^
SyntaxError: invalid syntax
[2024-02-02T10:37:43.884+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:43.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.103 seconds
[2024-02-02T10:37:47.889+0000] {processor.py:153} INFO - Started process (PID=1342) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:47.891+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:47.892+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:47.892+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:47.908+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:47.906+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:37:47.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:47.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.070 seconds
[2024-02-02T10:37:48.897+0000] {processor.py:153} INFO - Started process (PID=1343) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:48.899+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:48.900+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:48.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:48.903+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:48.902+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1,task2,task3] >> taskdummy >> [task2
                                             ^
SyntaxError: unexpected EOF while parsing
[2024-02-02T10:37:48.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:48.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.038 seconds
[2024-02-02T10:37:53.190+0000] {processor.py:153} INFO - Started process (PID=1357) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:53.194+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:53.196+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:53.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:53.200+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:53.198+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 23
    [task1,task2,task3] >> taskdummy >> [task5,tas
                                                 ^
SyntaxError: unexpected EOF while parsing
[2024-02-02T10:37:53.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:53.229+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.048 seconds
[2024-02-02T10:37:55.604+0000] {processor.py:153} INFO - Started process (PID=1363) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:37:55.606+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:37:55.607+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:55.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:55.619+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:37:55.618+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:37:55.620+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:37:55.645+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.049 seconds
[2024-02-02T10:38:00.855+0000] {processor.py:153} INFO - Started process (PID=1390) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:00.857+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:00.858+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:00.858+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:00.869+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:00.868+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:00.870+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:00.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.051 seconds
[2024-02-02T10:38:06.327+0000] {processor.py:153} INFO - Started process (PID=1405) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:06.328+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:06.329+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:06.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:06.336+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:06.335+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:06.336+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:06.365+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.042 seconds
[2024-02-02T10:38:11.703+0000] {processor.py:153} INFO - Started process (PID=1420) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:11.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:11.707+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:11.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:11.724+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:11.716+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:11.725+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:11.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.065 seconds
[2024-02-02T10:38:17.017+0000] {processor.py:153} INFO - Started process (PID=1447) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:17.021+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:17.022+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:17.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:17.030+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:17.029+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:17.031+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:17.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.042 seconds
[2024-02-02T10:38:22.646+0000] {processor.py:153} INFO - Started process (PID=1462) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:22.647+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:22.648+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:22.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:22.657+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:22.656+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:22.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:22.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.046 seconds
[2024-02-02T10:38:27.901+0000] {processor.py:153} INFO - Started process (PID=1486) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:27.910+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:27.912+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:27.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:27.922+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:27.920+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:27.923+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:27.954+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.064 seconds
[2024-02-02T10:38:33.176+0000] {processor.py:153} INFO - Started process (PID=1503) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:33.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:33.178+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:33.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:33.185+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:33.184+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:33.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:33.212+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.041 seconds
[2024-02-02T10:38:38.290+0000] {processor.py:153} INFO - Started process (PID=1518) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:38.291+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:38.292+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:38.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:38.301+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:38.300+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:38.302+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:38.332+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.049 seconds
[2024-02-02T10:38:43.399+0000] {processor.py:153} INFO - Started process (PID=1543) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:43.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:43.401+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:43.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:43.409+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:43.408+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:43.409+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:43.432+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.039 seconds
[2024-02-02T10:38:48.705+0000] {processor.py:153} INFO - Started process (PID=1558) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:48.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:48.708+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:48.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:48.718+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:48.718+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:48.719+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:48.747+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.048 seconds
[2024-02-02T10:38:53.802+0000] {processor.py:153} INFO - Started process (PID=1573) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:53.803+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:53.804+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:53.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:53.815+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:53.814+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:53.816+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:53.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.056 seconds
[2024-02-02T10:38:59.368+0000] {processor.py:153} INFO - Started process (PID=1600) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:38:59.369+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:38:59.370+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:59.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:59.377+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:38:59.376+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:38:59.378+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:38:59.403+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.038 seconds
[2024-02-02T10:39:04.516+0000] {processor.py:153} INFO - Started process (PID=1615) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:04.517+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:04.518+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:04.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:04.528+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:04.527+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:04.528+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:04.557+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.047 seconds
[2024-02-02T10:39:10.099+0000] {processor.py:153} INFO - Started process (PID=1639) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:10.100+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:10.101+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:10.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:10.117+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:10.116+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:10.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:10.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.079 seconds
[2024-02-02T10:39:15.596+0000] {processor.py:153} INFO - Started process (PID=1657) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:15.597+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:15.598+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:15.598+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:15.607+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:15.605+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:15.607+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:15.635+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.043 seconds
[2024-02-02T10:39:20.898+0000] {processor.py:153} INFO - Started process (PID=1672) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:20.899+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:20.899+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:20.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:20.906+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:20.905+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:20.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:20.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.038 seconds
[2024-02-02T10:39:26.227+0000] {processor.py:153} INFO - Started process (PID=1700) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:26.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:26.229+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:26.228+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:26.236+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:26.235+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:26.236+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:26.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.040 seconds
[2024-02-02T10:39:31.423+0000] {processor.py:153} INFO - Started process (PID=1715) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:31.424+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:31.426+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:31.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:31.435+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:31.434+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:31.436+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:31.471+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.055 seconds
[2024-02-02T10:39:36.817+0000] {processor.py:153} INFO - Started process (PID=1737) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:36.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:36.820+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:36.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:36.862+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:36.856+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:36.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:36.902+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.103 seconds
[2024-02-02T10:39:42.286+0000] {processor.py:153} INFO - Started process (PID=1757) to work on /opt/airflow/dags/dammy.py
[2024-02-02T10:39:42.289+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dammy.py for tasks to queue
[2024-02-02T10:39:42.290+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:42.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:42.298+0000] {logging_mixin.py:137} INFO - [2024-02-02T10:39:42.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dammy.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dammy.py", line 4, in <module>
    from airflow.operators.bash_dummy import BashDummy
ModuleNotFoundError: No module named 'airflow.operators.bash_dummy'
[2024-02-02T10:39:42.298+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dammy.py
[2024-02-02T10:39:42.323+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dammy.py took 0.043 seconds
