[2024-01-27T17:24:14.606+0000] {processor.py:153} INFO - Started process (PID=181876) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:14.607+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:14.609+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:14.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:14.648+0000] {processor.py:753} INFO - DAG(s) dict_keys(['daggroup']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:14.800+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:14.800+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:24:14.870+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:14.869+0000] {dag.py:3441} INFO - Setting next_dagrun for daggroup to None, run_after=None
[2024-01-27T17:24:14.928+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.327 seconds
[2024-01-27T17:24:20.106+0000] {processor.py:153} INFO - Started process (PID=181899) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:20.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:20.109+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:20.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:20.145+0000] {processor.py:753} INFO - DAG(s) dict_keys(['daggroup']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:20.173+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:20.172+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:24:20.250+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:20.250+0000] {dag.py:3441} INFO - Setting next_dagrun for daggroup to None, run_after=None
[2024-01-27T17:24:20.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.185 seconds
[2024-01-27T17:24:24.768+0000] {processor.py:153} INFO - Started process (PID=181906) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:24.769+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:24.771+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:24.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:24.790+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:24.787+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:24:24.790+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:24.837+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.074 seconds
[2024-01-27T17:24:30.717+0000] {processor.py:153} INFO - Started process (PID=181916) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:30.718+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:30.719+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:30.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:30.733+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:30.732+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:24:30.733+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:30.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.055 seconds
[2024-01-27T17:24:36.521+0000] {processor.py:153} INFO - Started process (PID=181938) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:36.522+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:36.523+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:36.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:36.535+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:36.533+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:24:36.535+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:36.564+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.050 seconds
[2024-01-27T17:24:42.226+0000] {processor.py:153} INFO - Started process (PID=181948) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:42.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:42.229+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:42.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:42.249+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:42.247+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:24:42.250+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:42.276+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.056 seconds
[2024-01-27T17:24:47.891+0000] {processor.py:153} INFO - Started process (PID=181970) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:47.895+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:47.897+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:47.897+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:47.916+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:47.915+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:24:47.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:47.946+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.061 seconds
[2024-01-27T17:24:53.008+0000] {processor.py:153} INFO - Started process (PID=181980) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:53.009+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:53.010+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:53.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:53.027+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:53.026+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:24:53.028+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:53.060+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.058 seconds
[2024-01-27T17:24:58.347+0000] {processor.py:153} INFO - Started process (PID=182000) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:58.349+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:24:58.350+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:58.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:58.369+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:24:58.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:24:58.369+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:24:58.410+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.071 seconds
[2024-01-27T17:25:03.489+0000] {processor.py:153} INFO - Started process (PID=182013) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:03.491+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:03.491+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:03.491+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:03.501+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:03.500+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:03.502+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:03.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.039 seconds
[2024-01-27T17:25:08.760+0000] {processor.py:153} INFO - Started process (PID=182023) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:08.762+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:08.764+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:08.764+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:08.783+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:08.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:08.784+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:08.826+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.073 seconds
[2024-01-27T17:25:14.680+0000] {processor.py:153} INFO - Started process (PID=182045) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:14.681+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:14.688+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:14.688+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:14.713+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:14.711+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:14.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:14.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.099 seconds
[2024-01-27T17:25:20.409+0000] {processor.py:153} INFO - Started process (PID=182055) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:20.411+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:20.412+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:20.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:20.429+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:20.428+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:20.430+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:20.464+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.061 seconds
[2024-01-27T17:25:25.575+0000] {processor.py:153} INFO - Started process (PID=182072) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:25.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:25.577+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:25.577+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:25.592+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:25.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:25.592+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:25.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.049 seconds
[2024-01-27T17:25:31.143+0000] {processor.py:153} INFO - Started process (PID=182084) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:31.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:31.146+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:31.146+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:31.160+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:31.159+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:31.160+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:31.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.054 seconds
[2024-01-27T17:25:37.000+0000] {processor.py:153} INFO - Started process (PID=182094) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:37.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:37.003+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:37.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:37.022+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:37.019+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:37.022+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:37.063+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.087 seconds
[2024-01-27T17:25:42.777+0000] {processor.py:153} INFO - Started process (PID=182116) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:42.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:42.780+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:42.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:42.805+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:42.803+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:42.805+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:42.841+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.072 seconds
[2024-01-27T17:25:48.712+0000] {processor.py:153} INFO - Started process (PID=182126) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:48.725+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:48.726+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:48.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:48.758+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:48.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:48.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:48.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.094 seconds
[2024-01-27T17:25:53.825+0000] {processor.py:153} INFO - Started process (PID=182145) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:53.826+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:53.827+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:53.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:53.837+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:53.837+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:53.838+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:53.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.045 seconds
[2024-01-27T17:25:59.769+0000] {processor.py:153} INFO - Started process (PID=182158) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:59.772+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:25:59.773+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:59.773+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:59.786+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:25:59.785+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:25:59.786+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:25:59.810+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.047 seconds
[2024-01-27T17:26:05.102+0000] {processor.py:153} INFO - Started process (PID=182168) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:05.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:05.104+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:05.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:05.120+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:05.119+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:05.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:05.154+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.057 seconds
[2024-01-27T17:26:10.401+0000] {processor.py:153} INFO - Started process (PID=182190) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:10.402+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:10.402+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:10.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:10.413+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:10.412+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:10.414+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:10.440+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.044 seconds
[2024-01-27T17:26:16.320+0000] {processor.py:153} INFO - Started process (PID=182200) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:16.320+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:16.321+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:16.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:16.335+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:16.333+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:16.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:16.360+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.046 seconds
[2024-01-27T17:26:21.743+0000] {processor.py:153} INFO - Started process (PID=182222) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:21.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:21.744+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:21.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:21.755+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:21.755+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:21.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:21.784+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.048 seconds
[2024-01-27T17:26:27.512+0000] {processor.py:153} INFO - Started process (PID=182232) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:27.513+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:27.513+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:27.513+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:27.525+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:27.524+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:27.526+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:27.548+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.043 seconds
[2024-01-27T17:26:33.460+0000] {processor.py:153} INFO - Started process (PID=182249) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:33.461+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:33.462+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:33.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:33.472+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:33.471+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:33.473+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:33.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.043 seconds
[2024-01-27T17:26:39.248+0000] {processor.py:153} INFO - Started process (PID=182264) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:39.253+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:39.256+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:39.255+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:39.277+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:39.276+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:39.277+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:39.301+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.062 seconds
[2024-01-27T17:26:44.940+0000] {processor.py:153} INFO - Started process (PID=182274) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:44.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:44.942+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:44.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:44.960+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:44.959+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:44.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:44.998+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.065 seconds
[2024-01-27T17:26:50.712+0000] {processor.py:153} INFO - Started process (PID=182296) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:50.714+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:50.715+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:50.714+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:50.728+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:50.727+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:50.729+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:50.752+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.050 seconds
[2024-01-27T17:26:56.398+0000] {processor.py:153} INFO - Started process (PID=182306) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:56.399+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:26:56.399+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:56.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:56.414+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:26:56.413+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:26:56.415+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:26:56.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.047 seconds
[2024-01-27T17:27:01.574+0000] {processor.py:153} INFO - Started process (PID=182325) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:01.575+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:01.577+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:01.576+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:01.589+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:01.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:01.589+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:01.617+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.049 seconds
[2024-01-27T17:27:06.742+0000] {processor.py:153} INFO - Started process (PID=182338) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:06.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:06.744+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:06.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:06.759+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:06.758+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:06.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:06.782+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.048 seconds
[2024-01-27T17:27:12.559+0000] {processor.py:153} INFO - Started process (PID=182348) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:12.560+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:12.561+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:12.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:12.578+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:12.577+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:12.579+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:12.609+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.056 seconds
[2024-01-27T17:27:18.219+0000] {processor.py:153} INFO - Started process (PID=182370) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:18.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:18.221+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:18.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:18.237+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:18.236+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:18.237+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:18.273+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.060 seconds
[2024-01-27T17:27:24.099+0000] {processor.py:153} INFO - Started process (PID=182380) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:24.101+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:24.103+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:24.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:24.122+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:24.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:24.122+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:24.148+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.065 seconds
[2024-01-27T17:27:30.015+0000] {processor.py:153} INFO - Started process (PID=182399) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:30.015+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:30.016+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:30.016+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:30.027+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:30.026+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:30.028+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:30.054+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.043 seconds
[2024-01-27T17:27:35.101+0000] {processor.py:153} INFO - Started process (PID=182412) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:35.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:35.103+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:35.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:35.115+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:35.114+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:35.116+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:35.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.052 seconds
[2024-01-27T17:27:40.388+0000] {processor.py:153} INFO - Started process (PID=182422) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:40.391+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:40.393+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:40.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:40.409+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:40.408+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:40.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:40.442+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.059 seconds
[2024-01-27T17:27:45.614+0000] {processor.py:153} INFO - Started process (PID=182445) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:45.615+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:45.615+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:45.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:45.626+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:45.625+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:45.626+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:45.649+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.039 seconds
[2024-01-27T17:27:51.257+0000] {processor.py:153} INFO - Started process (PID=182452) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:51.258+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:51.258+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:51.258+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:51.276+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:51.274+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:51.277+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:51.311+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.060 seconds
[2024-01-27T17:27:56.400+0000] {processor.py:153} INFO - Started process (PID=182471) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:56.401+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:27:56.403+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:56.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:56.422+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:27:56.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:27:56.423+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:27:56.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.065 seconds
[2024-01-27T17:28:01.577+0000] {processor.py:153} INFO - Started process (PID=182484) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:01.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:01.579+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:01.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:01.589+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:01.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:01.590+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:01.611+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.038 seconds
[2024-01-27T17:28:06.814+0000] {processor.py:153} INFO - Started process (PID=182488) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:06.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:06.815+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:06.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:06.826+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:06.825+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:06.827+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:06.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.044 seconds
[2024-01-27T17:28:12.080+0000] {processor.py:153} INFO - Started process (PID=182511) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:12.082+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:12.084+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:12.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:12.123+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:12.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:12.124+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:12.167+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.097 seconds
[2024-01-27T17:28:17.227+0000] {processor.py:153} INFO - Started process (PID=182521) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:17.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:17.228+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:17.228+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:17.240+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:17.239+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:17.241+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:17.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.042 seconds
[2024-01-27T17:28:22.940+0000] {processor.py:153} INFO - Started process (PID=182531) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:22.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:22.941+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:22.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:22.952+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:22.951+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:22.952+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:22.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.039 seconds
[2024-01-27T17:28:28.192+0000] {processor.py:153} INFO - Started process (PID=182554) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:28.193+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:28.194+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:28.194+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:28.213+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:28.211+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:28.214+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:28.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.069 seconds
[2024-01-27T17:28:33.951+0000] {processor.py:153} INFO - Started process (PID=182564) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:33.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:33.953+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:33.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:33.965+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:33.964+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:33.965+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:33.990+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.043 seconds
[2024-01-27T17:28:39.830+0000] {processor.py:153} INFO - Started process (PID=182584) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:39.831+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:39.832+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:39.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:39.872+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:39.870+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:39.872+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:39.942+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.126 seconds
[2024-01-27T17:28:45.088+0000] {processor.py:153} INFO - Started process (PID=182597) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:45.090+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:45.091+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:45.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:45.103+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:45.102+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:45.104+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:45.127+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.044 seconds
[2024-01-27T17:28:50.971+0000] {processor.py:153} INFO - Started process (PID=182607) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:50.971+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:50.972+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:50.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:50.983+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:50.982+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:50.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:51.009+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.042 seconds
[2024-01-27T17:28:56.849+0000] {processor.py:153} INFO - Started process (PID=182629) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:56.853+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:28:56.853+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:56.853+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:56.864+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:28:56.863+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:28:56.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:28:56.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.046 seconds
[2024-01-27T17:29:01.933+0000] {processor.py:153} INFO - Started process (PID=182639) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:01.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:01.935+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:01.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:01.946+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:01.945+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:01.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:01.971+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.042 seconds
[2024-01-27T17:29:07.203+0000] {processor.py:153} INFO - Started process (PID=182655) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:07.204+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:07.209+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:07.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:07.236+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:07.235+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:07.237+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:07.293+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.102 seconds
[2024-01-27T17:29:12.367+0000] {processor.py:153} INFO - Started process (PID=182668) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:12.368+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:12.370+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:12.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:12.388+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:12.387+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:12.389+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:12.421+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.060 seconds
[2024-01-27T17:29:17.772+0000] {processor.py:153} INFO - Started process (PID=182673) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:17.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:17.776+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:17.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:17.830+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:17.825+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:17.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:17.881+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.122 seconds
[2024-01-27T17:29:23.851+0000] {processor.py:153} INFO - Started process (PID=182696) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:23.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:23.862+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:23.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:23.911+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:23.910+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:23.912+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:23.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.157 seconds
[2024-01-27T17:29:29.101+0000] {processor.py:153} INFO - Started process (PID=182706) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:29.105+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:29.106+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:29.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:29.121+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:29.120+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:29.122+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:29.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.055 seconds
[2024-01-27T17:29:35.163+0000] {processor.py:153} INFO - Started process (PID=182716) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:35.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:35.168+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:35.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:35.190+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:35.188+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:35.190+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:35.218+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.074 seconds
[2024-01-27T17:29:40.704+0000] {processor.py:153} INFO - Started process (PID=182738) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:40.705+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:40.718+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:40.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:40.756+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:40.750+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:40.757+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:40.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.192 seconds
[2024-01-27T17:29:46.205+0000] {processor.py:153} INFO - Started process (PID=182748) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:46.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:46.212+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:46.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:46.246+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:46.244+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:46.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:46.318+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.124 seconds
[2024-01-27T17:29:51.640+0000] {processor.py:153} INFO - Started process (PID=182758) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:51.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:51.642+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:51.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:51.657+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:51.656+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:51.657+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:51.694+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.060 seconds
[2024-01-27T17:29:58.979+0000] {processor.py:153} INFO - Started process (PID=182781) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:58.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:29:58.990+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:58.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:59.065+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:29:59.058+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:29:59.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:29:59.186+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.242 seconds
[2024-01-27T17:30:04.304+0000] {processor.py:153} INFO - Started process (PID=182791) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:04.305+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:04.307+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:04.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:04.320+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:04.319+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:04.321+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:04.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.056 seconds
[2024-01-27T17:30:09.901+0000] {processor.py:153} INFO - Started process (PID=182799) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:09.902+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:09.902+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:09.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:09.914+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:09.913+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:09.914+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:09.940+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.045 seconds
[2024-01-27T17:30:15.072+0000] {processor.py:153} INFO - Started process (PID=182822) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:15.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:15.092+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:15.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:15.191+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:15.159+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:15.191+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:15.324+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.274 seconds
[2024-01-27T17:30:20.548+0000] {processor.py:153} INFO - Started process (PID=182831) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:20.557+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:20.558+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:20.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:20.614+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:20.608+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:20.614+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:20.669+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.127 seconds
[2024-01-27T17:30:25.797+0000] {processor.py:153} INFO - Started process (PID=182840) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:25.799+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:25.801+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:25.801+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:25.822+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:25.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:25.822+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:25.857+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.067 seconds
[2024-01-27T17:30:31.072+0000] {processor.py:153} INFO - Started process (PID=182861) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:31.090+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:31.091+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:31.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:31.117+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:31.116+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:31.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:31.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.182 seconds
[2024-01-27T17:30:36.467+0000] {processor.py:153} INFO - Started process (PID=182871) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:36.470+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:36.473+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:36.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:36.507+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:36.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:36.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:36.541+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.093 seconds
[2024-01-27T17:30:41.591+0000] {processor.py:153} INFO - Started process (PID=182881) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:41.595+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:41.596+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:41.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:41.621+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:41.619+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:41.621+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:41.658+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.075 seconds
[2024-01-27T17:30:46.730+0000] {processor.py:153} INFO - Started process (PID=182900) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:46.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:46.746+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:46.746+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:46.799+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:46.787+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:46.800+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:46.910+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.195 seconds
[2024-01-27T17:30:52.123+0000] {processor.py:153} INFO - Started process (PID=182912) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:52.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:52.125+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:52.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:52.142+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:52.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:52.142+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:52.197+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.080 seconds
[2024-01-27T17:30:57.618+0000] {processor.py:153} INFO - Started process (PID=182922) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:57.619+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:30:57.621+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:57.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:57.640+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:30:57.638+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:30:57.640+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:30:57.696+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.090 seconds
[2024-01-27T17:31:03.284+0000] {processor.py:153} INFO - Started process (PID=182944) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:03.285+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:03.286+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:03.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:03.302+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:03.301+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:31:03.303+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:03.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.061 seconds
[2024-01-27T17:31:08.741+0000] {processor.py:153} INFO - Started process (PID=182954) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:08.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:08.743+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:08.743+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:08.761+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:08.759+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:31:08.762+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:08.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.060 seconds
[2024-01-27T17:31:14.679+0000] {processor.py:153} INFO - Started process (PID=182964) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:14.680+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:14.682+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:14.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:14.705+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:14.703+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:31:14.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:14.747+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.075 seconds
[2024-01-27T17:31:19.896+0000] {processor.py:153} INFO - Started process (PID=182986) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:19.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:19.902+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:19.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:19.938+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:19.933+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dagrundag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dagrundag.py", line 21, in <module>
    tsk_group = TaskGroup("Ingestão",dag=dag)
NameError: name 'TaskGroup' is not defined
[2024-01-27T17:31:19.939+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:20.027+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.144 seconds
[2024-01-27T17:31:24.199+0000] {processor.py:153} INFO - Started process (PID=182995) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:24.201+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:24.203+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:24.202+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:24.234+0000] {processor.py:753} INFO - DAG(s) dict_keys(['daggroup']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:24.360+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:24.360+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:24.410+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:24.410+0000] {dag.py:3441} INFO - Setting next_dagrun for daggroup to None, run_after=None
[2024-01-27T17:31:24.453+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.260 seconds
[2024-01-27T17:31:29.689+0000] {processor.py:153} INFO - Started process (PID=183004) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:29.691+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:29.692+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:29.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:29.735+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Dag']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:30.203+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:30.203+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:Dag
[2024-01-27T17:31:30.288+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:30.288+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:Dag
[2024-01-27T17:31:30.325+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:30.325+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:Dag
[2024-01-27T17:31:30.326+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:30.326+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:30.375+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:30.375+0000] {dag.py:2711} INFO - Creating ORM DAG for Dag
[2024-01-27T17:31:30.432+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:30.431+0000] {dag.py:3441} INFO - Setting next_dagrun for Dag to None, run_after=None
[2024-01-27T17:31:30.546+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.863 seconds
[2024-01-27T17:31:35.848+0000] {processor.py:153} INFO - Started process (PID=183024) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:35.849+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:35.850+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:35.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:35.951+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Dag']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:35.998+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:35.998+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:36.118+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:36.118+0000] {dag.py:3441} INFO - Setting next_dagrun for Dag to None, run_after=None
[2024-01-27T17:31:36.187+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.347 seconds
[2024-01-27T17:31:41.285+0000] {processor.py:153} INFO - Started process (PID=183037) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:41.286+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:41.287+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:41.286+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:41.307+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Dag']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:41.326+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:41.325+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:41.363+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:41.363+0000] {dag.py:3441} INFO - Setting next_dagrun for Dag to None, run_after=None
[2024-01-27T17:31:41.391+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.110 seconds
[2024-01-27T17:31:46.428+0000] {processor.py:153} INFO - Started process (PID=183045) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:46.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:46.430+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:46.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:46.448+0000] {processor.py:753} INFO - DAG(s) dict_keys(['Dag']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:46.463+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:46.463+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:46.494+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:46.494+0000] {dag.py:3441} INFO - Setting next_dagrun for Dag to None, run_after=None
[2024-01-27T17:31:46.515+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.092 seconds
[2024-01-27T17:31:49.279+0000] {processor.py:153} INFO - Started process (PID=183050) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:49.281+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:49.282+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:49.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:49.308+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:49.506+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:49.506+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:dagrundag
[2024-01-27T17:31:49.530+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:49.529+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:dagrundag
[2024-01-27T17:31:49.543+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:49.543+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:dagrundag
[2024-01-27T17:31:49.543+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:49.543+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:49.571+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:49.571+0000] {dag.py:2711} INFO - Creating ORM DAG for dagrundag
[2024-01-27T17:31:49.594+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:49.593+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag to None, run_after=None
[2024-01-27T17:31:49.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.351 seconds
[2024-01-27T17:31:51.687+0000] {processor.py:153} INFO - Started process (PID=183061) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:51.688+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:51.689+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:51.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:51.731+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:52.047+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:52.046+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:52.138+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:52.138+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:31:52.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.549 seconds
[2024-01-27T17:31:58.045+0000] {processor.py:153} INFO - Started process (PID=183075) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:58.050+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:31:58.051+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:58.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:58.100+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:31:58.130+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:58.130+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:31:58.221+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:31:58.221+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:31:58.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.250 seconds
[2024-01-27T17:32:03.650+0000] {processor.py:153} INFO - Started process (PID=183085) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:03.651+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:03.652+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:03.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:03.705+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:03.747+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:03.747+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:03.837+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:03.837+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:03.943+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.308 seconds
[2024-01-27T17:32:09.059+0000] {processor.py:153} INFO - Started process (PID=183107) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:09.060+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:09.063+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:09.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:09.089+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:09.114+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:09.113+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:09.174+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:09.173+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:09.213+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.159 seconds
[2024-01-27T17:32:14.529+0000] {processor.py:153} INFO - Started process (PID=183117) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:14.530+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:14.532+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:14.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:14.580+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:14.608+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:14.608+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:14.674+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:14.673+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:14.706+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.184 seconds
[2024-01-27T17:32:19.861+0000] {processor.py:153} INFO - Started process (PID=183127) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:19.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:19.863+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:19.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:19.891+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:19.918+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:19.918+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:19.976+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:19.976+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:20.020+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.167 seconds
[2024-01-27T17:32:25.243+0000] {processor.py:153} INFO - Started process (PID=183150) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:25.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:25.246+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:25.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:25.284+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:25.401+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:25.401+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:25.450+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:25.450+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:25.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.249 seconds
[2024-01-27T17:32:30.554+0000] {processor.py:153} INFO - Started process (PID=183160) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:30.558+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:30.559+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:30.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:30.593+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:30.622+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:30.621+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:30.789+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:30.789+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:30.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.324 seconds
[2024-01-27T17:32:36.517+0000] {processor.py:153} INFO - Started process (PID=183179) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:36.519+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:36.520+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:36.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:36.555+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:36.620+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:36.620+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:36.909+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:36.908+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:37.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.509 seconds
[2024-01-27T17:32:42.110+0000] {processor.py:153} INFO - Started process (PID=183193) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:42.111+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:42.112+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:42.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:42.148+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:42.176+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:42.176+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:42.237+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:42.237+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:42.273+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.169 seconds
[2024-01-27T17:32:47.351+0000] {processor.py:153} INFO - Started process (PID=183203) to work on /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:47.352+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dagrundag.py for tasks to queue
[2024-01-27T17:32:47.354+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:47.354+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:47.397+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dagrundag2']) retrieved from /opt/airflow/dags/dagrundag.py
[2024-01-27T17:32:47.432+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:47.431+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-01-27T17:32:47.519+0000] {logging_mixin.py:137} INFO - [2024-01-27T17:32:47.519+0000] {dag.py:3441} INFO - Setting next_dagrun for dagrundag2 to None, run_after=None
[2024-01-27T17:32:47.568+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dagrundag.py took 0.224 seconds
