[2024-02-03T18:34:42.123+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-02-03T17:00:00+00:00 [queued]>
[2024-02-03T18:34:42.142+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: email_test.tsk4 scheduled__2024-02-03T17:00:00+00:00 [queued]>
[2024-02-03T18:34:42.142+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-03T18:34:42.143+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-02-03T18:34:42.143+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-03T18:34:42.169+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk4> on 2024-02-03 17:00:00+00:00
[2024-02-03T18:34:42.175+0000] {standard_task_runner.py:55} INFO - Started process 120 to run task
[2024-02-03T18:34:42.180+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'email_test', 'tsk4', 'scheduled__2024-02-03T17:00:00+00:00', '--job-id', '586', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmphjzgqsgw']
[2024-02-03T18:34:42.181+0000] {standard_task_runner.py:83} INFO - Job 586: Subtask tsk4
[2024-02-03T18:34:42.282+0000] {task_command.py:388} INFO - Running <TaskInstance: email_test.tsk4 scheduled__2024-02-03T17:00:00+00:00 [running]> on host 5b3777e64f6c
[2024-02-03T18:34:42.397+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_test
AIRFLOW_CTX_TASK_ID=tsk4
AIRFLOW_CTX_EXECUTION_DATE=2024-02-03T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-03T17:00:00+00:00
[2024-02-03T18:34:42.399+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-02-03T18:34:42.399+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-02-03T18:34:42.416+0000] {subprocess.py:86} INFO - Output:
[2024-02-03T18:34:42.418+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-03T18:34:42.443+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-03T18:34:42.449+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=email_test, task_id=tsk4, execution_date=20240203T170000, start_date=20240203T183442, end_date=20240203T183442
[2024-02-03T18:34:42.484+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:152: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-03T18:34:42.485+0000] {email.py:268} INFO - Email alerting: attempt 1
[2024-02-03T18:34:44.732+0000] {email.py:280} INFO - Sent an alert email to ['guilherme.ribeiro.business@gmail.com']
[2024-02-03T18:34:46.873+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 586 for task tsk4 (Bash command failed. The command returned a non-zero exit code 1.; 120)
[2024-02-03T18:34:46.889+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-03T18:34:46.956+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
