[2024-02-12T18:58:47.287+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: windturbine.group_database.insert_data manual__2024-02-12T18:58:30.253119+00:00 [queued]>
[2024-02-12T18:58:47.312+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: windturbine.group_database.insert_data manual__2024-02-12T18:58:30.253119+00:00 [queued]>
[2024-02-12T18:58:47.312+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-12T18:58:47.312+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-02-12T18:58:47.313+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-12T18:58:47.347+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): group_database.insert_data> on 2024-02-12 18:58:30.253119+00:00
[2024-02-12T18:58:47.358+0000] {standard_task_runner.py:55} INFO - Started process 607 to run task
[2024-02-12T18:58:47.374+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'windturbine', 'group_database.insert_data', 'manual__2024-02-12T18:58:30.253119+00:00', '--job-id', '1096', '--raw', '--subdir', 'DAGS_FOLDER/windturbine.py', '--cfg-path', '/tmp/tmp3toktnu5']
[2024-02-12T18:58:47.378+0000] {standard_task_runner.py:83} INFO - Job 1096: Subtask group_database.insert_data
[2024-02-12T18:58:47.502+0000] {task_command.py:388} INFO - Running <TaskInstance: windturbine.group_database.insert_data manual__2024-02-12T18:58:30.253119+00:00 [running]> on host b5b8d61630c3
[2024-02-12T18:58:47.655+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=guilherme.ribeiro.business@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=windturbine
AIRFLOW_CTX_TASK_ID=group_database.insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-02-12T18:58:30.253119+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-12T18:58:30.253119+00:00
[2024-02-12T18:58:47.655+0000] {sql.py:254} INFO - Executing: INSERT INTO sensors (idtemp, powerfactor,
                               hydraulicpressure, temperature, timestamp)
                               VALUES (%s, %s, %s, %s, %s);
[2024-02-12T18:58:47.676+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-02-12T18:58:48.298+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-02-12T18:58:48.305+0000] {sql.py:375} INFO - Running statement: INSERT INTO sensors (idtemp, powerfactor,
                               hydraulicpressure, temperature, timestamp)
                               VALUES (%s, %s, %s, %s, %s);, parameters: ('{{ ti.xcom_pull(task_ids="get_data",key="idtemp") }}', '{{ ti.xcom_pull(task_ids="get_data",key="powerfactor") }}', '{{ ti.xcom_pull(task_ids="get_data",key="hydraulicpressure") }}', '{{ ti.xcom_pull(task_ids="get_data",key="temperature") }}', '{{ ti.xcom_pull(task_ids="get_data",key="timestamp") }}')
[2024-02-12T18:58:48.306+0000] {sql.py:384} INFO - Rows affected: 1
[2024-02-12T18:58:48.327+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=windturbine, task_id=group_database.insert_data, execution_date=20240212T185830, start_date=20240212T185847, end_date=20240212T185848
[2024-02-12T18:58:48.354+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-02-12T18:58:48.384+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
